### ISSUE TITLE
Demo crashes in simulator

### ISSUE THREAD

**Issue by paresh-navadiya** [NSRare/NSGIF#1]
Reason : Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Source type 1 not available'

As its not handled while using image picker in simulator

**Comment by sebyddd** [comment]
Yes, got to add this to prevent the simulator from crashing.
`if ([UIImagePickerController isSourceTypeAvailable:UIImagePickerControllerSourceTypeCamera])`

Will add in the next release, as I am currently working on some big changes on the main branch.

**Comment by sebyddd** [comment]
Fixed in 69ba09ba21f9370099cfefe2347e18627d97f098.
Thank you.
