### ISSUE TITLE
Create GIF From UIImage array

### ISSUE THREAD

**Issue by itsjc** [NSRare/NSGIF#12]
Any advice on how this could be done? Thanks for your help

**Comment by sebyddd** [comment]
The target of the library is to turn videos into GIFs, but you can easily manage to get an images array to work. I advise you to use the `createGIFforTimePoints` method to generate the GIF from your array.

Best,
Sebastian

**Comment by itsjc** [comment]
Can I pay you to make the switch?

**Comment by sebyddd** [comment]
@itsjc, you can email me and we could discuss this custom task.

**Comment by jacobokoenig** [comment]
Hi, can I use this on macOS? If so, how could I make a GIF from an array of stored images?
