### ISSUE TITLE
Black screen issue with AVPlayer when running createGIFfromURL

### ISSUE THREAD

**Issue by dlush315** [NSRare/NSGIF#20]
I have an AVPlayer with a video and when I run the createGIFfromURL block, it I go home while it's working and reopen the app, the AVPlayer turns black. However, after a while, if I come back to the app , the AVPlayer returns to the screen. 

Any ideas as to why this is happening and/or how to fix it?

**Comment by kaushikpatel1396** [comment]
@dlush315  any luck?
