### ISSUE TITLE
How to release memory?

### ISSUE THREAD

**Issue by qyzhaojinxi** [NSRare/NSGIF#7]
Hi ,it really helps me a lot.But when I convert a lot times,it takes some memory.I can't free these memory.Can you help me?

**Comment by sebyddd** [comment]
The memory is released after the conversion is done. Can you elaborate your issue, please?

**Comment by qyzhaojinxi** [comment]
I called the method:

```
  [NSGIF optimalGIFfromURL:videoURL loopCount:0 fileName:[filename stringByDeletingPathExtension]  completion:^(NSURL *GifURL) {
        }];
```

in GCD 

```
     dispatch_queue_t queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0);


    dispatch_group_t group = dispatch_group_create();

    dispatch_group_async(group, queue, ^{

           //call the mothod here

});

      dispatch_group_notify(group, dispatch_get_main_queue(), ^{
      NSLog(@"finished");
    });
```

When I finish this task,the memory is not freed.Even if I pop this Viewcontroller.

**Comment by sebyddd** [comment]
No need to wrap it in an asynchronous block. The library already handles all power consuming task on a different thread. 

Is the conversion finished when you are popping the controller?

**Comment by qyzhaojinxi** [comment]
Yes,the conversion is finished.The reason why I write like this  is that there are other tasks in  gcd group and I want to know when all  tasks are finished.

**Comment by vernalkick** [comment]
I've been getting memory warnings when the video is more than just a few seconds. I wonder if it's related.

**Comment by melakamc** [comment]
Yes. The memory seems not to be released once the conversion happens :/ crashes after a few conversions.

**Comment by cassidyclawson** [comment]
I can also confirm a memory leak. For me it adds about the same amount of memory as the size of the gif per conversion.

**Comment by cassidyclawson** [comment]
I posted a $100 bounty for a fix to this bug, available to anyone (including the original author).
https://www.bountysource.com/issues/31041391-gif-conversion-creates-memory-leak

**Comment by sebyddd** [comment]
Follow #9.

**Comment by qyzhaojinxi** [comment]
ok

**Comment by aiyub007** [comment]
Solve this bug please memory leak is big problem

**Comment by sebyddd** [comment]
@aiyub007 – I don't have the time to properly address this issue. Solving this would require a rebuild from scratch of the GIF instead of building it on top of selected frames from the video. If you need this fixed by any means, you can [hire me](http://dobrincu.co/hire) to do that.
