### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by cassidyclawson** [NSRare/NSGIF#8]
Hi guys,

Great library! Thanks for building this.

I would like to add additional compression to the gifs. It's my understanding that this can be done by reducing the number of colors or increasing redundant patterns along scan lines.

[Gifscicle](https://www.lcdf.org/gifsicle/) is a command line utility that can compress gifs. [Cloudinary](http://cloudinary.com/blog/lossy_compression_for_optimizing_animated_gifs) is a cloud platform that can do it, too. So I know it's possible but it doesn't look to be easy in Objective-C and Core Graphics. 

Does anyone have any advice? Any freelance developers looking for a quick gig?

**Comment by sebyddd** [comment]
Hi Cassidy,

Didn't thought about compression yet. I think it might be achievable. Shoot me an email at me@dobrincu.co, so we can chat about it. :)
